#!/bin/bash
#přehraje video z youtube skopirovane do schránky, tedy "http://....."
#leafpad ~/skr/mpv_youtube
##urxvt -geometry 80x20+60+150 -title Video_online +hold -e bash -c "mpv '$(xsel --clipboard)' --ytdl --ytdl-format=243,134,43,18 --fs --ontop --initial-audio-sync --slang=cs --alang=cs  --hwdec=auto --hwdec-codecs=h264,mpeg2video"
urxvt -geometry 80x20+60+150 -title Video_online +hold -e bash -c "mpv '$(xsel --clipboard)' --ytdl --ytdl-format=243,134,43,18 --fs --volume=50 --initial-audio-sync --slang=cs,en --alang=cs,en  -ytdl-raw-options=write-auto-sub=,sub-lang=cs --sub-ass-force-margins --sub-spacing=1 --sub-bold=yes --sub-border-size=3 --sub-shadow-offset=3 --sub-shadow-color=0/0/0/0.5 --sub-use-margins=no --no-sub-visibility --hwdec=auto --force-window"

#; wait && kill $(pidof)
#-title Video_online
#xterm -title Video_online -e "mpv `youtube-dl $(xsel --clipboard) -f 36  -g`"
