#!/bin/sh -e
#
# Usage:
#   ytpl song title
#   ytpl < titles
#
xterm -geometry 80x20-40-40 -fa 'Monospace' -fs 14 -title "Youtube_zvuk" -e bash -c '

echo "==> Bude se prehravat jen zvuk z Youtube<=="
echo "==> Cele okno ukoncis => ctrl-c <=="
echo "==> Napis co hledas na Youtube <=="
go() {
    echo "==> Zadal si co chces na Youtube <=="
    echo "==> Teda hraji z Youtube => ... |> $1 ... <=="

    # Force TTY input for controls even if titles are read from input
    mpv --vid=no --fs=no "$(youtube-dl -g "ytsearch:$1" | tail -1)" < /dev/tty
}

#mpv --vid=no --fs=no "$(youtube-dl -g "ytsearch:$1" | tail -1)" < /dev/tty

# All arguments as a single space separated string
if [ -n "$*" ]; then

    go "$*"
    exit
fi

#echo "==Napiste dalsi co hledáte na youtube=="
# Read one title per line
while read title; do
    go "$title"
done
 '